versionGroups:
  - dependencies: ["@ngutil/**"]
    dependencyTypes: ["!local"]
    pinVersion: workspace:*
    label: "@ngutil packages should only be under peerDependencies with workspace:*"

sortFirst:
  - name
  - version
  - author
  - description
  - scripts
