/* eslint-disable */
/**
 * This file was automatically generated by json-schema-to-typescript.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run json-schema-to-typescript to regenerate this file.
 */

export interface SvgToTsExecutorSchema {
    /**
     * Prefix of every generated varaibales
     */
    prefix?: string
    /**
     * Different icon set configurations
     */
    sets: {
        /**
         * Input svg files
         */
        files: (
            | string
            | {
                  /**
                   * Input svg file
                   */
                  file: string
                  /**
                   * Generated name in ts file
                   */
                  name: string
              }
        )[]
        /**
         * Generated ts file path
         */
        output: string
        /**
         * Various svg overrides
         */
        overrides?: (
            | {
                  /**
                   * Add class to the root svg element
                   */
                  addClass: string[]
              }
            | {
                  /**
                   * Add or remove attributes based on value
                   */
                  attributes: {
                      /**
                       * This interface was referenced by `undefined`'s JSON-Schema definition
                       * via the `patternProperty` "^.*$".
                       */
                      [k: string]: string | null
                  }
              }
        )[]
    }[]
}
